version: '3.8'

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  db-data:

networks:
  spring-network:
    driver: bridge
